-- ============================================================
-- 迁移脚本: 004_add_tools_system.sql
-- 版本: 2.3.0
-- 创建时间: 2026-05-06
-- 说明: 新增工具分类 + 工具管理模块
-- 设计文档: docs/superpowers/specs/2026-05-06-工具管理模块设计文档.md
-- ============================================================

USE `superadmin_db`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- ------------------------------------------------------------
-- 1. 工具分类表
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `tool_categories` (
  `id`           INT UNSIGNED     NOT NULL AUTO_INCREMENT,
  `code`         VARCHAR(30)      NOT NULL                 COMMENT '分类编码',
  `name`         VARCHAR(50)      NOT NULL                 COMMENT '分类名称',
  `icon`         VARCHAR(500)     DEFAULT NULL             COMMENT '分类图标 URL',
  `description`  VARCHAR(500)     DEFAULT NULL             COMMENT '分类描述',
  `sort`         INT              NOT NULL DEFAULT 0       COMMENT '排序（越小越前）',
  `status`       TINYINT UNSIGNED NOT NULL DEFAULT 1       COMMENT '状态:0禁用,1启用',
  `created_at`   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code`           (`code`),
  INDEX       `idx_status_sort`  (`status`, `sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工具分类表';


-- ------------------------------------------------------------
-- 2. 工具表
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `tools` (
  `id`                   BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `code`                 VARCHAR(60)      NOT NULL                          COMMENT '工具编码（前端路由 slug）',
  `name`                 VARCHAR(80)      NOT NULL                          COMMENT '工具名称',
  `description`          VARCHAR(500)     NOT NULL DEFAULT ''               COMMENT '工具描述',
  `keyword`              VARCHAR(500)     NOT NULL DEFAULT ''               COMMENT '搜索关键字（管道分隔）',
  `category_id`          INT UNSIGNED     NOT NULL                          COMMENT '分类ID',
  `category_code`        VARCHAR(30)      NOT NULL                          COMMENT '分类编码（冗余，便于筛选）',
  `icon`                 VARCHAR(500)     NOT NULL DEFAULT ''               COMMENT '工具图标',
  `color`                VARCHAR(20)      NOT NULL DEFAULT ''               COMMENT '主题色（#HEX）',
  `path`                 VARCHAR(200)     NOT NULL DEFAULT ''               COMMENT '前端路由路径',
  `is_feature`           TINYINT UNSIGNED NOT NULL DEFAULT 0                COMMENT '是否特色:0否,1是',
  `required_level_code`  VARCHAR(30)      NOT NULL DEFAULT 'free'           COMMENT '最低成长等级要求',
  `require_paid`         TINYINT UNSIGNED NOT NULL DEFAULT 0                COMMENT '是否要求付费:0否,1是',
  `status`               TINYINT UNSIGNED NOT NULL DEFAULT 0                COMMENT '状态:0下架,1已发布',
  `sort`                 INT              NOT NULL DEFAULT 0                COMMENT '同分类内排序',
  `created_at`           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code`                    (`code`),
  INDEX       `idx_status`                (`status`),
  INDEX       `idx_cat_status_sort`       (`category_code`, `status`, `sort`),
  INDEX       `idx_feature_status`        (`is_feature`, `status`),
  INDEX       `idx_required_level`        (`required_level_code`),
  INDEX       `idx_require_paid`          (`require_paid`),
  CONSTRAINT `fk_tool_category` FOREIGN KEY (`category_id`)
    REFERENCES `tool_categories` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工具表';


-- ============================================================
-- 种子数据
-- 11 个分类 + 233 个工具（来源 test1.js）
-- 全部默认: status=1, is_feature=0, required_level_code='free', require_paid=0
-- ============================================================

-- 11 个工具分类（来源 test1.js 的 categorys 常量）
INSERT IGNORE INTO `tool_categories` (`code`, `name`, `icon`, `description`, `sort`, `status`) VALUES
('DAILY', '日常应用', NULL, NULL, 0, 1),
('DOCUMENT', '文档编辑', NULL, NULL, 1, 1),
('QUERY', '信息查询', NULL, NULL, 2, 1),
('CALCULATION', '计算转换', NULL, NULL, 3, 1),
('VIDEO', '视频处理', NULL, NULL, 4, 1),
('AUDIO', '音频处理', NULL, NULL, 5, 1),
('IMAGE', '图片处理', NULL, NULL, 6, 1),
('TEXT', '文本优化', NULL, NULL, 7, 1),
('DEV', '开发工具', NULL, NULL, 8, 1),
('LIFE', '生活工具', NULL, NULL, 9, 1),
('INTELLIGENT', '智能应用', NULL, NULL, 10, 1);

-- 233 个工具（来源 test1.js，全部默认 status=1 已发布、is_feature=0、required_level_code='free'、require_paid=0）
INSERT IGNORE INTO `tools`
  (`code`, `name`, `description`, `keyword`, `category_id`, `category_code`, `icon`, `color`, `path`,
   `is_feature`, `required_level_code`, `require_paid`, `status`, `sort`)
VALUES
('gold-price', '今日黄金价格', '实时黄金价格查询', '黄金|价格|行情|投资',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/gold-price',
   0, 'free', 0, 1, 1),
('oil-price', '全国油价查询', '全国最新油价查询', '油价|汽油|柴油|加油站',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/local_gas_station_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/oil-price',
   0, 'free', 0, 1, 2),
('horoscope', '星座运势', '十二星座今日运势查询', '星座|运势|占卜|白羊|金牛|双子|巨蟹|狮子|处女|天秤|天蝎|射手|摩羯|水瓶|双鱼',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/cookie_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/horoscope',
   0, 'free', 0, 1, 3),
('relationship-calculator', '亲戚称呼换算', '亲戚称呼计算', '亲戚|称呼|关系|家庭',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/egg_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/relationship-calculator',
   0, 'free', 0, 1, 4),
('calculator', '计算器', '标准/科学计算器', '计算器|科学计算器|四则运算|sin|cos|tan|log|ln|开方',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/functions_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D81B60', '/calculator',
   0, 'free', 0, 1, 1),
('exchange-rate-converter', '汇率换算', '实时汇率换算', '汇率|换算|货币|外汇|兑换|美元|人民币|欧元|日元',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/universal_currency_alt_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8E24AA', '/exchange-rate-converter',
   0, 'free', 0, 1, 2),
('realtime-exchange-rate', '实时汇率', '实时汇率查询与换算', '汇率|实时|货币|外汇|兑换|查询',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/universal_currency_alt_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#5E35B1', '/realtime-exchange-rate',
   0, 'free', 0, 1, 3),
('number-to-chinese', '数字转中文', '数字金额转中文大写', '数字|中文|大写|金额|人民币|转换',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/number_to_chinese_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/number-to-chinese',
   0, 'free', 0, 1, 1),
('chinese-converter', '简繁转换', '在线简繁体中文转换工具，支持简体转繁体、繁体转简体，一键转换，方便快捷。', '简繁转换|简体|繁体|中文转换|繁简转换',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/translate_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/chinese-converter',
   0, 'free', 0, 1, 2),
('text-to-pinyin', '文字转拼音', '在线中文汉字转拼音工具，支持多音字识别，一键转换，方便快捷。', '文字转拼音|汉字转拼音|拼音转换|注音|读音',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/text_to_pinyin_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/text-to-pinyin',
   0, 'free', 0, 1, 3),
('dialect-translator', '方言翻译', '在线方言翻译工具，支持粤语、闽南语、上海话、四川话、东北话等多种方言与普通话互译。', '方言翻译|粤语翻译|闽南语翻译|上海话翻译|东北话翻译|方言转换',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_translate_e2c.svg', '#00ACC1', '/dialect-translator',
   0, 'free', 0, 1, 1),
('cantonese-translator', '粤语互译', '在线粤语（广东话）与普通话互译工具，支持粤语转国语、国语转粤语，一键翻译，沟通无障碍。', '粤语翻译|广东话翻译|粤语转国语|国语转粤语|白话翻译',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_text.svg', '#00897B', '/cantonese-translator',
   0, 'free', 0, 1, 2),
('translation', '在线翻译', '多语言在线互译工具，支持中文、英语、日语、韩语等多种语言互译', '在线翻译|多语言翻译|中英互译|翻译工具',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_translate_c2e.svg', '#43A047', '/translation',
   0, 'free', 0, 1, 3),
('unit-converter', '单位换算', '常用单位快速换算', '单位换算|单位转换|长度|面积|体积|质量|纳米|微米|毫米|厘米|米|千米',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/ic_public_rotate.svg', '#FB8C00', '/unit-converter',
   0, 'free', 0, 1, 4),
('money-management-calculator', '理财计算', '理财计算工具', '理财计算|投资收益|利息计算|复利计算|财务计算',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/account_balance_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F4511E', '/money-management-calculator',
   0, 'free', 0, 1, 5),
('pension-calculator', '养老金计算', '养老金计算器', '养老金|退休金|社保|退休',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/elderly_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#E53935', '/pension-calculator',
   0, 'free', 0, 1, 6),
('individual-income-tax-calculator', '个税计算', '个人所得税计算器', '个税|所得税|工资|年终奖|劳务',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/receipt_long_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D32F2F', '/individual-income-tax-calculator',
   0, 'free', 0, 1, 7),
('house-loan-calculator', '房贷计算', '房贷计算器', '房贷|商业贷款|公积金贷款|组合贷款|等额本息|等额本金',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/house_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D81B60', '/house-loan-calculator',
   0, 'free', 0, 1, 8),
('car-loan-calculator', '车贷计算', '车贷计算器', '车贷|汽车贷款|等额本息|等额本金',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/directions_car_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8E24AA', '/car-loan-calculator',
   0, 'free', 0, 1, 9),
('profit-calculator', '收益计算', '收益计算器', '收益|计算|增幅|正推|反推|利润|投资',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/trending_up_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#5E35B1', '/profit-calculator',
   0, 'free', 0, 1, 10),
('fuel-consumption-calculator', '油耗计算', '油耗计算器 - 计算百公里油耗和每公里成本', '油耗|计算|百公里|成本|加油|行驶',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/local_gas_station_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8B5CF6', '/fuel-consumption-calculator',
   0, 'free', 0, 1, 11),
('network-calculator', '网络计算', '网络计算器 - 支持IP地址、子网掩码、广播地址计算及网络规划', '网络|计算|IP|子网|掩码|广播|规划',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/router_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1E88E5', '/network-calculator',
   0, 'free', 0, 1, 12),
('date-calculator', '日期计算器', '日期计算器 - 计算两个日期之间的天数，或根据日期推算前后日期', '日期|计算|天数|推算|间隔|日历',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/calendar_month_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/date-calculator',
   0, 'free', 0, 1, 13),
('time-calculator', '时间计算器', '时间计算器 - 支持时间加减和日期加减计算', '时间|计算|加减|日期|间隔|时长',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/time-calculator',
   0, 'free', 0, 1, 14),
('retirement-age-calculator', '退休年龄计算', '退休年龄计算器 - 根据最新政策计算延迟退休年龄和时间', '退休|年龄|计算|延迟|政策|社保',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/work_history_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1976D2', '/retirement-age-calculator',
   0, 'free', 0, 1, 15),
('compound-interest-calculator', '复利计算', '复利计算器 - 支持按年、月、日复利计算', '复利|计算|利息|本金|投资|理财',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/auto_graph_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1565C0', '/compound-interest-calculator',
   0, 'free', 0, 1, 16),
('fancy-name-generator', '花式昵称生成', '在线生成花式昵称，支持删除线、下划线、花藤字等30+种特效', '花式昵称|昵称生成|花藤字|菊花文|特殊符号|网名生成',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/glyphs_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/fancy-name-generator',
   0, 'free', 0, 1, 4),
('text-editor', '文本编辑器', '在线文本编辑工具，支持去除空格、空行、换行，全角半角转换等功能', '文本编辑|去除空格|去除空行|全角半角|文本处理',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/edit_square_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/text-editor',
   0, 'free', 0, 1, 5),
('id-card-converter', '身份证转换', '15位与18位身份证号码相互转换，自动计算校验码', '身份证|转换|15位|18位|校验码|证件',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/id_card_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/id-card-converter',
   0, 'free', 0, 1, 6),
('text-crypto', '文本加解密', '支持AES加密解密、MD5摘要、SHA256摘要等多种加密算法', '文本加密|AES|MD5|SHA256|加解密|摘要|哈希',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/lock_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#673AB7', '/text-crypto',
   0, 'free', 0, 1, 7),
('work-value-calculator', '工作性价比', '工作性价比计算器 - 综合评估薪资、通勤、环境等因素', '工作性价比|薪资|通勤|职场|评估|计算器',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/functions_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#E91E63', '/work-value-calculator',
   0, 'free', 0, 1, 17),
('currency-converter', '汇率转换', '货币汇率转换', '汇率|货币|转换|美元',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/change_circle_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/currency-converter',
   0, 'free', 0, 1, 5),
('calendar', '万年历', '公历农历节气查询', '万年历|日历|农历|节气',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/calendar_month_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/calendar',
   0, 'free', 0, 1, 6),
('history-today', '历史今日', '查看历史上的今天', '历史|今天|事件|回顾',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/ic_history_today.svg', '#8f4b2e', '/history-today',
   0, 'free', 0, 1, 7),
('hot-list', '即时热榜', '查看全网热门话题榜单', '热榜|热搜|百度|微博|抖音|知乎',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/newspaper_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#f71b0c', '/hot-list',
   0, 'free', 0, 1, 8),
('morning-paper', '每日早报', '每天60秒读懂世界', '早报|新闻|每日|60秒|世界',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/ic_public_worldclock_filled.svg', '#060af1', '/morning-paper',
   0, 'free', 0, 1, 9),
('news-center', '新闻资讯', '聚合全网最新热门新闻资讯', '新闻|资讯|热点|时事|科技|娱乐',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/newspaper_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/news-center',
   0, 'free', 0, 1, 10),
('movie-boxoffice', '电影票房', '实时查询电影票房排行榜', '电影|票房|排行|影视|院线',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/movie_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#000000', '/movie-boxoffice',
   0, 'free', 0, 1, 11),
('gold-history', '金价历史', '查看黄金价格历史走势', '金价|黄金|历史|走势|价格',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/gold-history',
   0, 'free', 0, 1, 12),
('holiday-countdown', '节日倒数', '重要节日倒计时', '节日|倒数|节气|时间',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/calendar_month_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/holiday-countdown',
   0, 'free', 0, 1, 13),
('daily-quote', '每日一言', '每日随机获取一句经典语录', '一言|语录|名言|每日|经典',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/oneword.svg', '#8B5CF6', '/daily-quote',
   0, 'free', 0, 1, 14),
('daily-english', '每日英语', '每日一句英语名言，支持中英对照和朗读', '英语|名言|每日|学习|翻译',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/translate_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/daily-english',
   0, 'free', 0, 1, 15),
('weather-forecast', '天气预报', '实时天气预报查询', '天气|预报|温度|气象|下雨',
   (SELECT id FROM `tool_categories` WHERE code='DAILY'), 'DAILY',
   '/assets/imgs/weather_snowy_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/weather-forecast',
   0, 'free', 0, 1, 16),
('hardware-ranking', '天梯排行', '手机CPU、桌面CPU、桌面显卡性能天梯排行榜', '性能|排行|天梯图|CPU|显卡|手机|桌面',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/speed_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/hardware-ranking',
   0, 'free', 0, 1, 4),
('funny-jokes', '搞笑段子', '随机获取搞笑段子，开心每一天', '搞笑|段子|笑话|幽默|娱乐',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/mood_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FFC107', '/funny-jokes',
   0, 'free', 0, 1, 5),
('couplet-generator', '对联生成', '智能对联生成工具', '对联|生成|上联|下联|春联',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/writing.svg', '#E53935', '/couplet-generator',
   0, 'free', 0, 1, 6),
('garbage-classification', '垃圾分类', '垃圾分类查询助手', '垃圾|分类|回收|干垃圾|湿垃圾|有害垃圾',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/delete_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#4CAF50', '/garbage-classification',
   0, 'free', 0, 1, 7),
('gold-reserve', '世界黄金储备', '查看世界各国黄金储备数据及趋势', '黄金|储备|世界|排名|趋势',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#0D47A1', '/gold-reserve',
   0, 'free', 0, 1, 8),
('beast-language', '兽语互译', '兽语加密解密工具，将文字转换为兽语（呜嗷啊）或反向解码', '兽语|加密|解密|呜嗷啊|恶搞|聊天',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/translate_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#673AB7', '/beast-language',
   0, 'free', 0, 1, 9),
('speak-well', '好好说话', '网络流行语缩写查询', '好好说话|缩写|拼音|网络用语|yyds',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/chat_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1296db', '/speak-well',
   0, 'free', 0, 1, 1),
('sentence-query', '据意查句', '根据意思查找名言佳句', '据意查句|名言|佳句|古诗文|现代文|写作',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/library_books_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/sentence-query',
   0, 'free', 0, 1, 2),
('api-percent', 'API占比', '鸿蒙系统各API版本占比情况分布', 'API|占比|分布|鸿蒙|HarmonyOS',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/harmony_api_percent_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/api-percent',
   0, 'free', 0, 1, 3),
('cookbook-query', '菜谱查询', '在线菜谱查询，提供详细的做法和食材', '菜谱|美食|做法|烹饪|查询|食谱',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/restaurant_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/cookbook-query',
   0, 'free', 0, 1, 4),
('car-query', '车辆查询', '在线车辆信息查询，支持查询车辆品牌、型号、价格等详细信息', '车辆|汽车|品牌|型号|查询|宝马|奥迪|奔驰',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/directions_car_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/vehicle-query',
   0, 'free', 0, 1, 5),
('history-figure', '历史人物查询', '查询历史人物生平事迹和基本信息', '历史|人物|生平|事迹|朝代|查询',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/ic_contacts_business_cards.svg', '#795548', '/history-figure',
   0, 'free', 0, 1, 6),
('company-query', '企业查询', '全国企业工商信息查询', '企业|工商|查询|公司|信用代码',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/ic_contacts_company_filled.svg', '#2a5caa', '/company-query',
   0, 'free', 0, 1, 7),
('coordinate-query', '经纬度查询', '在线经纬度查询工具', '经纬度|坐标|查询|定位|地理',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/location_on_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/coordinate-query',
   0, 'free', 0, 1, 8),
('world-time', '世界时间', '全球主要城市实时时间查询', '时间|时区|世界|全球|时差',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#673AB7', '/world-time',
   0, 'free', 0, 1, 9),
('lottery-query', '彩票开奖查询', '全国彩票开奖结果查询', '彩票|开奖|双色球|大乐透|中奖',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/ic_public_search_filled.svg', '#f71b0c', '/lottery',
   0, 'free', 0, 1, 10),
('phone-query', '常用号码查询', '各类服务电话查询', '电话|号码|服务|查询',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/contact_phone_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/phone-query',
   0, 'free', 0, 1, 11),
('location-query', '归属地查询', '手机IP归属地查询', '归属地|手机号|IP|地址',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/location_on_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/location-query',
   0, 'free', 0, 1, 12),
('postcode-query', '邮编查询', '全国邮政编码查询', '邮编|邮政|编码|地址',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/pin_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/postcode-query',
   0, 'free', 0, 1, 13),
('capital-list', '世界各国首都大全', '世界各国首都查询', '首都|国家|城市|地理',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/location_city_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/capital-list',
   0, 'free', 0, 1, 14),
('ip-location', '全球IP查询', 'IP地址归属地查询', 'IP|地址|归属地|网络',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/location_on_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/ip-location',
   0, 'free', 0, 1, 15),
('phone-code-list', '国际电话区号大全', '国际电话区号查询', '区号|国际|电话|国家',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/phone_enabled_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/phone-code-list',
   0, 'free', 0, 1, 16),
('license-plate-list', '车牌号码查询', '车牌归属地查询', '车牌|号码|归属地|省份',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/universal_currency_alt_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/license-plate-list',
   0, 'free', 0, 1, 17),
('country-code-list', '国家地区简码信息表表', '国家地区ISO代码查询', '国家|简码|ISO|代码',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/globe_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/country-code-list',
   0, 'free', 0, 1, 18),
('linux-command', 'Linux命令查询', 'Linux命令用法详解查询', 'Linux|命令|查询|用法|参数|shell',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/developer_mode_tv_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#000000', '/linux-command',
   0, 'free', 0, 1, 19),
('id-card-validator', '身份证查询', '身份证号码验证', '身份证|查询|验证|号码',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/id_card_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/id-card-validator',
   0, 'free', 0, 1, 20),
('university-query', '高校查询', '全国高校信息查询', '高校|大学|查询|学校|代码',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/school_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#f71b0c', '/university-query',
   0, 'free', 0, 1, 21),
('trademark-query', '商标查询', '商标注册信息查询', '商标|注册|查询|品牌|知识产权',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/trademark.svg', '#1296db', '/trademark-query',
   0, 'free', 0, 1, 22),
('emoji-list', 'Emoji表情大全', 'Emoji表情符号查找复制', 'Emoji|表情|符号|复制|搜索',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/ic_public_emoji.svg', '#F39C12', '/emoji-list',
   0, 'free', 0, 1, 23),
('symbol-list', '常用特殊符号', '常用特殊符号查找复制', '符号|特殊符号|复制|搜索|箭头|爱心',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/symbol-list',
   0, 'free', 0, 1, 24),
('ascii-table', 'ASCII码表', 'ASCII字符对照表', 'ASCII|码表|字符|对照|控制字符',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#607D8B', '/ascii-table',
   0, 'free', 0, 1, 25),
('user-agent-tool', '浏览器UA查询', '浏览器UA信息查询', 'UA|UserAgent|浏览器|查询',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/highlight_mouse_cursor_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/user-agent-tool',
   0, 'free', 0, 1, 1),
('directory-tree-converter', '目录树转目录', '在线目录树结构与目录列表互转工具，支持生成JSON、Markdown等格式', '目录树,目录列表,结构转换,tree命令,文件结构',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/account_tree_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/directory-tree-converter',
   0, 'free', 0, 1, 2),
('browser-fingerprint', '浏览器指纹检测', '在线浏览器指纹检测工具，查看Canvas、WebGL、Audio等指纹信息', '浏览器指纹,Canvas指纹,WebGL指纹,设备指纹,隐私检测',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/fingerprint_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1565C0', '/browser-fingerprint',
   0, 'free', 0, 1, 3),
('json-extractor', 'JSON字段提取', '在线JSON字段提取工具', 'JSON提取,JSON解析,字段提取,数据处理,编程工具',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/data_object_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#0D47A1', '/json-extractor',
   0, 'free', 0, 1, 4),
('html-all-tags-remover', 'HTML标签去除', '在线HTML标签去除工具', 'HTML去除,标签去除,HTML清理,文本提取,纯文本',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/code_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#060af1', '/html-all-tags-remover',
   0, 'free', 0, 1, 5),
('cookie-to-json', 'Cookie转JSON', '在线Cookie转JSON工具', 'Cookie转换,Cookie转JSON,JSON转换,Cookie解析,开发工具',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/cookie_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#f71b0c', '/cookie-to-json',
   0, 'free', 0, 1, 6),
('crontab-calculator', 'Crontab表达式', '在线Crontab表达式计算与验证工具', 'Crontab,Cron表达式,定时任务,执行时间,Linux工具',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/crontab-calculator',
   0, 'free', 0, 1, 7),
('json-merger', 'JSON数据合并', '在线JSON数据合并工具，支持对象合并、数组合并、深度合并等多种模式', 'JSON合并,数据合并,JSON拼接,对象合并,开发工具',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/file_json_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/json-merger',
   0, 'free', 0, 1, 8),
('link-list-converter', '链接列表转超链接', '将纯文本链接列表批量转换为HTML、Markdown或BBCode格式的超链接', '链接转换,超链接,HTML链接,Markdown链接,批量转换',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/link_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/link-list-converter',
   0, 'free', 0, 1, 9),
('url-filename-extractor', '链接文件名提取', '批量提取URL链接中的文件名和扩展名', 'URL|提取|文件名|链接|解析',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/link_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/url-filename-extractor',
   0, 'free', 0, 1, 10),
('excel-to-json', 'Excel转JSON', '在线Excel文件转JSON工具，支持自定义表头、预览和格式化输出', 'Excel转JSON,XLSX转换,JSON转换,数据格式转换,开发工具',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/ic_files_spreadsheet_drive.svg', '#27AE60', '/excel-to-json',
   0, 'free', 0, 1, 11),
('html-preview', 'HTML运行', '在线HTML代码编辑与实时预览工具，支持iframe和新窗口预览模式', 'HTML预览,代码运行,前端工具,在线编辑器,实时预览',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/code_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/html-preview',
   0, 'free', 0, 1, 12),
('video-converter', '视频格式转换', '多种视频格式互转', '视频|格式|转换|MP4',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/video_file_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/video-converter',
   0, 'free', 0, 1, 1),
('video-compress', '视频压缩', '视频文件压缩', '视频|压缩|文件|大小',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/compress_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/video-compress',
   0, 'free', 0, 1, 2),
('audio-extractor', '视频提取音频', '提取视频中音频', '视频|音频|提取|分离',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/music_note_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#00a6ac', '/video-extract-audio',
   0, 'free', 0, 1, 3),
('video-speed', '视频变速', '视频播放速度调节', '视频|变速|速度|快慢',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/speed_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/video-speed',
   0, 'free', 0, 1, 4),
('video-merge', '视频拼接', '多段视频合并', '视频|拼接|合并|连接',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/join_left_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#ea66a6', '/video-merge',
   0, 'free', 0, 1, 5),
('video-cut', '视频裁剪', '裁剪视频片段', '视频|裁剪|剪切|片段',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/content_cut_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#D35400', '/video-cut',
   0, 'free', 0, 1, 6),
('video-volume', '视频音量修改', '调整视频音量', '视频|音量|声音|调整',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/volume_up_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/video-volume',
   0, 'free', 0, 1, 7),
('video-to-gif', '视频转GIF', '视频转GIF动图', '视频|GIF|动图|转换',
   (SELECT id FROM `tool_categories` WHERE code='VIDEO'), 'VIDEO',
   '/assets/imgs/gif_box_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/video-to-gif',
   0, 'free', 0, 1, 8),
('audio-converter', '音频格式转换', '多种音频格式互转', '音频|格式|转换|MP3',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/library_music_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/audio-converter',
   0, 'free', 0, 1, 1),
('audio-cut', '音频裁剪', '裁剪音频片段', '音频|裁剪|剪切|片段',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/content_cut_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#9C27B0', '/audio-cut',
   0, 'free', 0, 1, 2),
('audio-compress', '音频压缩', '音频文件压缩', '音频|压缩|文件|大小',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/compress_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/audio-compress',
   0, 'free', 0, 1, 3),
('audio-volume', '音频音量修改', '调整音频音量', '音频|音量|声音|调整',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/volume_up_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/audio-volume',
   0, 'free', 0, 1, 4),
('audio-speed', '音频调速', '音频播放速度调节', '音频|调速|速度|快慢',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/speed_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/audio-speed',
   0, 'free', 0, 1, 5),
('audio-merge', '音频拼接', '多段音频合并', '音频|拼接|合并|连接',
   (SELECT id FROM `tool_categories` WHERE code='AUDIO'), 'AUDIO',
   '/assets/imgs/join_left_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#9B59B6', '/audio-merge',
   0, 'free', 0, 1, 6),
('image-compress', '图片压缩', '图片文件压缩', '图片|压缩|文件|大小',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/compress_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/image-compress',
   0, 'free', 0, 1, 1),
('image-merge', '图片拼接', '图片拼接合成', '图片|拼接|合成|连接',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/transition_chop_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/image-merge',
   0, 'free', 0, 1, 2),
('image-resize', '修改图片尺寸', '自定义图片尺寸', '图片|尺寸|修改|自定义',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/checkbook_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/image-resize',
   0, 'free', 0, 1, 3),
('image-split', '图片水平/垂直均等切割', '图片水平/垂直均等切割', '图片|切割|均等|水平|垂直',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00ACC1', '/image-split',
   0, 'free', 0, 1, 4),
('image-batch-resize', '图片批量缩放', '批量调整多张图片尺寸，支持自定义大小、比例缩放', '图片|缩放|尺寸|批量|调整|大小',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/ic_image_batch_resize.svg', '#FF9800', '/image-batch-resize',
   0, 'free', 0, 1, 5),
('image-to-gif', '图片合成GIF', '多图合成GIF动图', '图片|GIF|动图|合成',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/gif_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/image-to-gif',
   0, 'free', 0, 1, 6),
('image-convert', '图片格式转换', '图片格式互相转换', '图片|格式|转换|JPG|PNG|WEBP',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/change_circle_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#27AE60', '/image-convert',
   0, 'free', 0, 1, 7),
('image-matting', '单色图像抠图', '在线单色背景图片抠图工具', '抠图|单色|背景|去除|透明',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/cleaning_services_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/image-matting',
   0, 'free', 0, 1, 8),
('image-crop', '图片裁剪', '在线图片裁剪工具', '图片|裁剪|剪切|头像|裁切',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/crop_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#E91E63', '/image-crop',
   0, 'free', 0, 1, 9),
('image-background', 'PNG图片背景色添加', '为PNG图片添加背景色', 'PNG背景色|图片背景|透明图片|背景填充|图片处理',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/image-background',
   0, 'free', 0, 1, 10),
('svg-preview', 'SVG预览工具', '在线SVG代码预览工具', 'SVG预览|SVG查看er|SVG代码|矢量图预览',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/ic_svg_preview.svg', '#FF9800', '/svg-preview',
   0, 'free', 0, 1, 11),
('color-preview', '颜色预览', '在线颜色预览与转换工具', '颜色预览|颜色转换|取色器|RGB转换|HEX转换|HSL转换|调色板',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/draw_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/color-preview',
   0, 'free', 0, 1, 12),
('qr-code-repair', '二维码修复', '在线二维码修复工具', '二维码修复|二维码去Logo|二维码修复工具|QR码修复|二维码美化',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/qr_code_2_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/qr-code-repair',
   0, 'free', 0, 1, 13),
('qr-code-generator', '二维码生成', '生成二维码', '二维码|生成|扫码|QR',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/qr_code_2_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/qr-code-generator',
   0, 'free', 0, 1, 14),
('gif-edit', 'GIF帧修改', '修改GIF动图的帧', 'GIF|编辑|帧|修改|动图',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/edit_square_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/gif-edit',
   0, 'free', 0, 1, 15),
('gif-split', 'GIF帧拆分', '将GIF拆分为静态图片', 'GIF|拆分|分解|图片|帧',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/content_cut_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#2a5caa', '/gif-split',
   0, 'free', 0, 1, 16),
('image-round', '图片圆角', '图片添加圆角', '图片|圆角|效果|边框',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/crop_rotate_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/image-round',
   0, 'free', 0, 1, 17),
('image-pixelate', '图片像素化马赛克', '图片马赛克效果', '图片|像素|马赛克|效果',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/comedy_mask_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/image-pixelate',
   0, 'free', 0, 1, 18),
('image-watermark', '图片水印平铺', '图片添加平铺水印', '图片|水印|平铺|添加',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/copyright_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/image-watermark',
   0, 'free', 0, 1, 19),
('image-invert', '图像反相/反色', '图像反相反色', '图像|反相|反色|处理',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/contrast_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/image-invert',
   0, 'free', 0, 1, 20),
('image-color-picker', '图片取色', '图片颜色提取', '图片|取色|颜色|提取',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/format_color_fill_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/image-color-picker',
   0, 'free', 0, 1, 21),
('handheld-danmu', '手持弹幕', '在线手持弹幕工具，支持自定义文字内容、大小、颜色和滚动速度，适用于各种聚会、演唱会场景', '手持弹幕|弹幕|滚动文字|自定义弹幕|演唱会',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/text_snippet_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00897B', '/handheld-danmu',
   0, 'free', 0, 1, 10),
('reaction-test', '反应力测试', '在线反应力测试工具，测试你的神经反应速度，挑战极限手速', '反应力测试,反应速度,手速测试,反应时间,游戏,测试工具',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/timer_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#4CAF50', '/reaction-test',
   0, 'free', 0, 1, 11),
('decision-maker', '做个决定', '在线转盘做决定工具', '做决定|转盘|选择困难症|随机选择|今天吃什么',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/change_circle_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#43A047', '/decision-maker',
   0, 'free', 0, 1, 12),
('weather-ranking', '天气排行', '全国天气气温实时排行榜', '天气|排行|气温|温度|排名',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/leaderboard_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/weather-ranking',
   0, 'free', 0, 1, 13),
('temperature-map', '全国气温图', '查看全国气温实时状况图', '气温|地图|天气|温度分布',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/globe_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FB8C00', '/temperature-map',
   0, 'free', 0, 1, 14),
('random-question', '随机弱智提问', '随机获取一个有趣的弱智问题及回答', '弱智吧|提问|段子|搞笑|幽默',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/mood_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/random-question',
   0, 'free', 0, 1, 15),
('brain-teasers', '脑筋急转弯', '随机获取一个脑筋急转弯问题及答案', '脑筋急转弯|智力题|谜语|搞笑',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/smart_toy_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#E91E63', '/brain-teasers',
   0, 'free', 0, 1, 16),
('crazy-thursday', '疯狂星期四', '随机获取疯狂星期四文案', '疯狂星期四|KFC|文案|段子|搞笑',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/smart_toy_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D32F2F', '/crazy-thursday',
   0, 'free', 0, 1, 17),
('caihongpi', '彩虹屁', '随机获取一句花式夸人彩虹屁', '彩虹屁|夸人|赞美|语录|搞笑',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_love.svg', '#F4511E', '/caihongpi',
   0, 'free', 0, 1, 18),
('solid-color-generator', '纯色图片生成', '生成纯色背景图', '纯色|图片|生成|背景',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/format_color_fill_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/solid-color-generator',
   0, 'free', 0, 1, 22),
('image-grayscale', '图像黑白化', '彩图转黑白效果', '图像|黑白|灰度|效果',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/contrast_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/image-grayscale',
   0, 'free', 0, 1, 23),
('base64-to-image', 'Base64转图片', 'Base64转图片', 'Base64|图片|编码|转换',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/functions_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/base64-to-image',
   0, 'free', 0, 1, 24),
('image-to-base64', '图片转Base64', '图片转Base64', '图片|Base64|编码|转换',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/functions_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/image-to-base64',
   0, 'free', 0, 1, 25),
('qr-code-scanner', '二维码解析', '识别二维码内容', '二维码|识别|解析|扫码',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/qr_code_2_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/qr-code-scanner',
   0, 'free', 0, 1, 26),
('pdf-to-doc', 'PDF转Word', 'PDF转Word文档', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/description_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/pdf-to-doc',
   0, 'free', 0, 1, 1),
('doc-to-pdf', '文档转PDF', '文档转PDF', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/picture_as_pdf_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/doc-to-pdf',
   0, 'free', 0, 1, 2),
('doc-to-image', '文档转图片', '文档转图片', '文档转图片|Word转图片|DOC转图片|DOCX转图片',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/image_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FFC107', '/doc-to-image',
   0, 'free', 0, 1, 3),
('pdf-merge', 'PDF合并', '合并多个PDF', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/stacks_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/pdf-merge',
   0, 'free', 0, 1, 4),
('pdf-compress', 'PDF压缩', 'PDF压缩与设置', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/picture_as_pdf_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/pdf-compress',
   0, 'free', 0, 1, 5),
('pdf-encrypt', 'PDF加密', 'PDF设置密码', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/picture_as_pdf_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/pdf-encrypt',
   0, 'free', 0, 1, 6),
('pdf-decrypt', 'PDF解密', '移除PDF密码', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/picture_as_pdf_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/pdf-decrypt',
   0, 'free', 0, 1, 7),
('image-to-pdf', '图片转PDF', '图片转PDF', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/picture_as_pdf_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/image-to-pdf',
   0, 'free', 0, 1, 8),
('pdf-to-image', 'PDF转图片', 'PDF转图片', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/image_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/pdf-to-image',
   0, 'free', 0, 1, 9),
('pdf-split', 'PDF拆分', '提取PDF页面', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/content_cut_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#D35400', '/pdf-split',
   0, 'free', 0, 1, 10),
('table-to-csv', '表格转CSV', 'Excel表格转CSV文件', 'Excel转CSV|表格转换|数据转换|xlsx转csv',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/ic_files_spreadsheet_drive.svg', '#27AE60', '/table-to-csv',
   0, 'free', 0, 1, 11),
('word-to-markdown', 'Word转Markdown', 'Word转Markdown格式', 'Word转Markdown|DOC转Markdown|文档转换|技术文档',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/description_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#795548', '/word-to-markdown',
   0, 'free', 0, 1, 12),
('markdown-to-file', 'Markdown转文档', 'Markdown转换', '',
   (SELECT id FROM `tool_categories` WHERE code='DOCUMENT'), 'DOCUMENT',
   '/assets/imgs/edit_document_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/markdown-to-file',
   0, 'free', 0, 1, 13),
('text-diff', '文本对比', '对比文本差异', '文本|对比|差异|比较',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/horizontal_split_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/text-diff',
   0, 'free', 0, 1, 8),
('english-fancy-text', '英文花字', '在线生成英文花样字体', '英文花字,花样字体,特殊字体,英文特效,字体生成器,Instagram字体,朋友圈字体',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/match_case_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/english-fancy-text',
   0, 'free', 0, 1, 9),
('chinese-segmentation', '中文分词', '在线中文分词工具，将中文句子拆分为独立的词语', '中文|分词|NLP|拆分|词语',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/horizontal_split_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/chinese-segmentation',
   0, 'free', 0, 1, 10),
('text-count', '字数统计', '统计文本字数', '字数|统计|文本|计数',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/looks_one_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/text-count',
   0, 'free', 0, 1, 11),
('text-replace', '文本替换', '正则文本替换', '文本|替换|正则|表达式',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/regular_expression_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/text-replace',
   0, 'free', 0, 1, 12),
('text-url-extractor', '文本提取网址', '提取文本URL', '文本|提取|网址|URL',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/link_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/text-url-extractor',
   0, 'free', 0, 1, 13),
('text-line-remover', '文本去空换行', '文本空行处理', '文本|去空|换行|处理',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/horizontal_rule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/text-line-remover',
   0, 'free', 0, 1, 14),
('text-deduplicator', '文本去重', '文本行去重', '文本|去重|行|重复',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/format_quote_off_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/text-deduplicator',
   0, 'free', 0, 1, 15),
('magic-text', '魔法文案', '在文案中插入不可见字符，规避检测', '魔法|文案|防检测|不可见字符|零宽',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/ic_magic_text.svg', '#9C27B0', '/magic-text',
   0, 'free', 0, 1, 16),
('number-extractor', '数字号码提取', '批量提取数字', '数字|号码|提取|批量',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/pin_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/number-extractor',
   0, 'free', 0, 1, 17),
('english-text-converter', '英文文本转换', '英文文本格式转换（大小写、命名规范等）', '英文|文本|转换|大小写|命名规范',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/english-text-converter',
   0, 'free', 0, 1, 18),
('link-extractor', '链接批量提取', '批量提取链接', '链接|批量|提取|文本',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/link_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/link-extractor',
   0, 'free', 0, 1, 19),
('ip-extractor', 'IP地址批量提取', '批量提取IP', 'IP|地址|批量|提取',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/bring_your_own_ip_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/ip-extractor',
   0, 'free', 0, 1, 20),
('text-prefix-suffix', '文本行前后添加', '添加前缀后缀', '文本|前缀|后缀|添加',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/align_justify_center_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/text-prefix-suffix',
   0, 'free', 0, 1, 21),
('keyword-filter', '关键词筛选过滤', '关键词筛选文本', '关键词|筛选|过滤|文本',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/filter_list_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/keyword-filter',
   0, 'free', 0, 1, 22),
('word-frequency', '词频统计', '文本词频统计', '词频|统计|文本|分析',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/flex_wrap_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/word-frequency',
   0, 'free', 0, 1, 23),
('unicode-converter', 'Unicode互转', '字符Unicode互转', 'Unicode|字符|编码|互转',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/screen_rotation_up_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/unicode-converter',
   0, 'free', 0, 1, 24),
('punctuation-converter', '中英文符号转换', '中英文标点互转', '中英文|符号|标点|转换',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/swap_horizontal_circle_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/punctuation-converter',
   0, 'free', 0, 1, 25),
('case-converter', '驼峰/下划线转换', '编程命名转换', '驼峰|下划线|命名|转换',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/format_underlined_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/case-converter',
   0, 'free', 0, 1, 26),
('datetime-formatter', '时间日期格式化', '时间日期格式转换', '时间|日期|格式化|转换',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/datetime-formatter',
   0, 'free', 0, 1, 27),
('json-parser', 'JSON解析', 'JSON格式化验证', 'JSON|解析|格式化|验证',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/file_json_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/json-parser',
   0, 'free', 0, 1, 28),
('regex-tester', '正则表达式测试', '正则测试工具', '正则|表达式|测试|工具',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/regular_expression_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/regex-tester',
   0, 'free', 0, 1, 29),
('regex-collection', '正则表达式大全', '常用正则大全', '正则|表达式|大全|常用',
   (SELECT id FROM `tool_categories` WHERE code='TEXT'), 'TEXT',
   '/assets/imgs/regular_expression_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/regex-collection',
   0, 'free', 0, 1, 30),
('bmi-calculator', 'BMI计算', 'BMI指数计算', 'BMI|身体|质量|指数',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/accessibility_new_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/bmi-calculator',
   0, 'free', 0, 1, 18),
('time-converter', '时间转换', '时间戳日期互转', '时间|时间戳|日期|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/time-converter',
   0, 'free', 0, 1, 19),
('area-converter', '面积转换', '面积单位转换', '面积|平方|单位|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/crop_square_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/area-converter',
   0, 'free', 0, 1, 20),
('volume-converter', '体积转换', '体积单位转换', '体积|立方|容量|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/package_2_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/volume-converter',
   0, 'free', 0, 1, 21),
('energy-converter', '功热转换', '功热单位转换', '功率|热量|能量|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/local_fire_department_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/energy-converter',
   0, 'free', 0, 1, 22),
('speed-converter', '速度转换', '速度单位转换', '速度|公里|英里|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/rocket_launch_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/speed-converter',
   0, 'free', 0, 1, 23),
('temperature-converter', '温度转换', '温度单位转换', '温度|摄氏|华氏|转换',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/device_thermostat_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/temperature-converter',
   0, 'free', 0, 1, 24),
('base-converter', '进制转换', '进制任意转换', '进制|转换|二进制|十六进制',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/counter_2_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/base-converter',
   0, 'free', 0, 1, 25),
('pregnancy-calculator', '预产期计算', '预产期计算', '预产期|怀孕|计算|孕期',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/baby_changing_station_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/pregnancy-calculator',
   0, 'free', 0, 1, 26),
('chinese-calendar-calculator', '日期天干地支计算', '在线日期天干地支计算器', '天干地支|农历计算|生肖查询|五行查询|中国传统历法',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/calendar_month_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/chinese-calendar-calculator',
   0, 'free', 0, 1, 27),
('menstrual-calculator', '生理期计算', '生理期计算', '生理期|月经|女性|计算',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/face_3_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/menstrual-calculator',
   0, 'free', 0, 1, 28),
('credit-card-apr-calculator', '信用卡利率计算', '信用卡分期真实年化利率计算器', '信用卡|分期|利率|年化|计算器|IRR',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/credit_card_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#E91E63', '/credit-card-apr-calculator',
   0, 'free', 0, 1, 29),
('dynasty-calculator', '历史朝代年份计算器', '中国历史朝代查询工具', '历史|朝代|年份|查询|时间轴',
   (SELECT id FROM `tool_categories` WHERE code='CALCULATION'), 'CALCULATION',
   '/assets/imgs/calendar_month_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/dynasty-calculator',
   0, 'free', 0, 1, 30),
('md5-digest', 'MD5摘要', '计算MD5摘要', 'MD5|摘要|哈希|加密',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/developer_mode_tv_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#1ABC9C', '/md5-digest',
   0, 'free', 0, 1, 13),
('base64-converter', 'Base64编码', '文本Base64互转', 'Base64|编码|解码|转换',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/heap_snapshot_large_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/base64-converter',
   0, 'free', 0, 1, 14),
('rc4-converter', 'RC4加密解密', 'RC4对称加密解密工具，支持自定义密钥的RC4算法加密解密', 'RC4加密|RC4解密|对称加密|数据加密|密钥加密',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/enhanced_encryption_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/rc4-converter',
   0, 'free', 0, 1, 15),
('url-encoder', 'URL编码', 'URL编码解码', 'URL|编码|解码|链接',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/frame_source_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/url-encode',
   0, 'free', 0, 1, 16),
('rsa-key-generator', 'RSA加密', 'RSA密钥生成', 'RSA|密钥|生成|公钥',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/vpn_key_generator_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#00a6ac', '/rsa-key-generator',
   0, 'free', 0, 1, 17),
('sha-encryption', 'SHA加密', 'SHA哈希加密', 'SHA|加密|哈希|摘要',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/enhanced_encryption_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/sha-encryption',
   0, 'free', 0, 1, 18),
('aes-encryption', 'AES加密', 'AES加密解密', 'AES|加密|解密|对称',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/security_key_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/aes-encryption',
   0, 'free', 0, 1, 19),
('js-obfuscator', 'JS混淆', 'JS代码混淆', 'JS|JavaScript|混淆|代码',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/javascript_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/js-obfuscator',
   0, 'free', 0, 1, 20),
('binary-converter', '二进制转文本', '二进制格式互转', '二进制|转换|文本|格式',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/folder_data_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/binary-converter',
   0, 'free', 0, 1, 21),
('css-to-js', 'CSS转JS工具', 'CSS转JS对象', 'CSS|JS|转换|样式',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/css_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2196F3', '/css-to-js',
   0, 'free', 0, 1, 22),
('html-tag-remover', 'HTML指定标签去除', 'HTML标签移除', 'HTML|标签|去除|移除',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/html_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/html-tag-remover',
   0, 'free', 0, 1, 23),
('user-agent-generator', 'UA生成', '生成UserAgent', 'UserAgent|生成|浏览器|设备',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/admin_panel_settings_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/user-agent-generator',
   0, 'free', 0, 1, 24),
('uuid-generator', 'UUID生成', '生成验证UUID', 'UUID|生成|验证|唯一',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/contextual_token_add_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#2a5caa', '/uuid-generator',
   0, 'free', 0, 1, 25),
('mac-generator', 'MAC随机生成', '生成随机MAC', 'MAC|地址|生成|网络',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/family_history_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3498DB', '/mac-generator',
   0, 'free', 0, 1, 26),
('barcode-generator', '条形码生成', '生成条形码', '条形码|生成|扫码|识别',
   (SELECT id FROM `tool_categories` WHERE code='IMAGE'), 'IMAGE',
   '/assets/imgs/barcode_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/barcode-generator',
   0, 'free', 0, 1, 27),
('file-base64-converter', 'Base64文件互转', '文件Base64互转', '文件|Base64|编码|转换',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/box_edit_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#45b97c', '/file-base64-converter',
   0, 'free', 0, 1, 27),
('xml-formatter', 'XML美化', 'XML美化压缩', 'XML|美化|压缩|格式化',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/folder_zip_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#F39C12', '/xml-formatter',
   0, 'free', 0, 1, 28),
('sql-formatter', 'SQL美化', 'SQL美化压缩', 'SQL|美化|压缩|数据库',
   (SELECT id FROM `tool_categories` WHERE code='DEV'), 'DEV',
   '/assets/imgs/database_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#ea66a6', '/sql-formatter',
   0, 'free', 0, 1, 29),
('document-correction', '文档校正', '文档图像自动矫正工具，支持自动识别文档边缘并进行透视矫正', '文档校正|图像矫正|透视变换|扫描件处理',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/ic_gallery_frame_overlay_rectify.svg', '#9C27B0', '/document-correction',
   0, 'free', 0, 1, 1),
('face-enhancement', '人脸清晰化', 'AI智能人脸修复工具，将模糊人脸变清晰，支持老照片修复', '人脸修复|照片清晰化|老照片修复|AI增强',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/ic_public_contacts_filled.svg', '#D35400', '/face-enhancement',
   0, 'free', 0, 1, 2),
('image-moire-removal', '图片去摩尔纹', '去除拍摄屏幕时产生的摩尔纹，还原图片真实细节', '去摩尔纹|屏幕纹去除|翻拍修复|图像优化',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/cleaning_services_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#8f4b2e', '/image-moire-removal',
   0, 'free', 0, 1, 3),
('image-to-link', '图片转链接', '图片上传生成链接工具，支持多种图片格式', '图床|图片链接|外链生成|图片分享',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/link_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#42A5F5', '/image-to-link',
   0, 'free', 0, 1, 4),
('remove-background', '智能抠图', 'AI智能识别主体，一键去除图片背景，支持人像、商品等', '抠图|去底|透明背景|证件照换底',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/cleaning_services_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg', '#2196F3', '/remove-background',
   0, 'free', 0, 1, 5),
('remove-watermark', '图片去水印', '智能涂抹去除图片中的水印、文字和杂物', '去水印|消除笔|图片修复|去字',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/healing_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/remove-watermark',
   0, 'free', 0, 1, 6),
('speech-to-text', '语音转文字', '音频文件转换为文字，支持多种音频格式和长语音识别', '语音转文字|录音转文字|音频听写|会议记录',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/change_circle_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9C27B0', '/speech-to-text',
   0, 'free', 0, 1, 7),
('table-ocr', '表格识别', '图片表格自动识别并导出为Excel文件，还原表格结构', '表格识别|表格OCR|图片转Excel|数据提取',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/ic_files_spreadsheet_drive.svg', '#45b97c', '/table-ocr',
   0, 'free', 0, 1, 8),
('text-recognition', '通用文字识别', '智能识别图片中的文字，支持手写体和印刷体', 'OCR|文字识别|拍照识字|图片转文字',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/price_change_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#42A5F5', '/text-recognition',
   0, 'free', 0, 1, 9),
('text-to-speech', '文本转语音', '智能文本转语音工具，支持多种声线和语调调节', '文本转语音|文字转语音|TTS|语音合成|配音',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/ic_public_switch_audio.svg', '#060af1', '/text-to-speech',
   0, 'free', 0, 1, 10),
('download-queue', '下载队列', '查看和管理所有的文件下载任务', '下载|队列|任务|管理',
   (SELECT id FROM `tool_categories` WHERE code='INTELLIGENT'), 'INTELLIGENT',
   '/assets/imgs/ic_public_view_list_filled.svg', '#1976D2', '/download-queue',
   0, 'free', 0, 1, 11),
('competition-grouping', '比赛活动分组', '在线比赛活动分组工具，支持自定义互斥规则，随机分组', '比赛|分组|活动|随机|互斥',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/groups_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D35400', '/competition-grouping',
   0, 'free', 0, 1, 19),
('password-generator', '随机密码生成', '强密码生成器，支持自定义长度、包含字符类型，保障账户安全', '密码|生成|随机|安全|强密码',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_random.svg', '#8f4b2e', '/password-generator',
   0, 'free', 0, 1, 20),
('random-lottery', '随机抽奖', '在线随机抽奖工具，支持自定义名单、奖项和抽取数量', '抽奖|随机|年会|活动|名单',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_random.svg', '#45b97c', '/random-lottery',
   0, 'free', 0, 1, 21),
('random-number', '随机数生成', '在线随机数生成器，支持自定义范围、生成数量和保留小数位', '随机数|生成|数字|范围',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_random.svg', '#9C27B0', '/random-number',
   0, 'free', 0, 1, 22),
('telegraph-translator', '电报码翻译', '摩斯密码/电报码在线翻译工具，支持文本与电报码互转', '电报|摩斯密码|翻译|转换|编码',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_translate_c2e.svg', '#2196F3', '/telegraph-translator',
   0, 'free', 0, 1, 23),
('visual-frame-rate-test', '可视帧率测试', '测试你眼睛的可视帧率极限，挑战不同显示时长的动态视力', '帧率测试,FPS测试,动态视力,视觉测试,眼力挑战',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_translate_c2e.svg', '#607D8B', '/visual-frame-rate-test',
   0, 'free', 0, 1, 24),
('mirror', '在线镜子', '在线镜子工具', '镜子,在线镜子,网络镜子,摄像头镜子,手机镜子,化妆镜',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_public_translate_c2e.svg', '#FF9800', '/mirror',
   0, 'free', 0, 1, 25),
('timer', '计时器', '在线倒计时器', '计时器|倒计时|定时器|Timer',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/schedule_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#3F51B5', '/timer',
   0, 'free', 0, 1, 26),
('electronic-wooden-fish', '电子木鱼', '在线电子木鱼，模拟真实木鱼敲击声音和动画，积攒功德，解压放松', '电子木鱼,功德,木鱼,解压,在线工具,敲木鱼',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/woodenfish.svg', '#E53935', '/electronic-wooden-fish',
   0, 'free', 0, 1, 27),
('coin-toss', '抛硬币', '在线抛硬币工具，模拟真实抛硬币动画和音效，帮你快速做决定', '抛硬币,投硬币,做决定,概率,随机,在线工具',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/coin_two.svg', '#D32F2F', '/coin-toss',
   0, 'free', 0, 1, 28),
('text-reading', '文本朗读', '在线文本朗读工具，支持中文、英文等多种语言，一键朗读文本内容', '文本朗读|语音朗读|文字转语音|TTS|朗读',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/volume_up_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#D81B60', '/text-reading',
   0, 'free', 0, 1, 29),
('drawing-board', '画板', '在线绘图画板，支持多种画笔、颜色选择，随时记录灵感', '画板|绘图|涂鸦|Drawing|Sketch',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/draw_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8E24AA', '/drawing-board',
   0, 'free', 0, 1, 30),
('magnifier', '在线放大镜', '在线放大镜工具，使用后置摄像头放大物体，支持画面冻结、补光灯、多倍变焦，方便阅读微小文字', '放大镜,在线放大镜,手机放大镜,变焦,微距,阅读辅助',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/ic_magnifier.svg', '#2196F3', '/magnifier',
   0, 'free', 0, 1, 31),
('stopwatch', '在线秒表', '精准在线秒表工具，支持分段计时、暂停/继续，毫秒级精度，极简设计', '秒表|计时器|Stopwatch|在线计时|分段计时',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/timer_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#5E35B1', '/stopwatch',
   0, 'free', 0, 1, 32),
('scoreboard', '记分牌', '简单好用的在线记分牌，支持双人/双队比分记录和计时功能', '记分牌|比分|计时|比赛|Scoreboard',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/leaderboard_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#8B5CF6', '/scoreboard',
   0, 'free', 0, 1, 33),
('color-blindness-test', '色盲检测', '专业色盲色弱在线检测工具', '色盲|色弱|检测|测试|红绿色盲|辨色力',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/colors_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/color-blindness-test',
   0, 'free', 0, 1, 34),
('synonym-antonym', '近反义词查询', '在线近义词、反义词查询工具', '近义词|反义词|同义词|词语|查询',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/swap_horiz_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF5722', '/synonym-antonym',
   0, 'free', 0, 1, 26),
('calorie-query', '卡路里查询', '在线食物卡路里查询工具', '卡路里|热量|食物|查询|减肥',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/cookie_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/calorie-query',
   0, 'free', 0, 1, 27),
('harassment-phone-query', '骚扰电话查询', '查询手机号码是否为骚扰电话', '骚扰|电话|手机号|拦截|查询',
   (SELECT id FROM `tool_categories` WHERE code='QUERY'), 'QUERY',
   '/assets/imgs/contact_phone_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#9B59B6', '/harassment-phone-query',
   0, 'free', 0, 1, 28),
('earthquake-warning', '地震预警', '实时地震信息查询', '地震|预警|震级|震中|速报',
   (SELECT id FROM `tool_categories` WHERE code='LIFE'), 'LIFE',
   '/assets/imgs/tsunami_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.svg', '#FF9800', '/earthquake-warning',
   0, 'free', 0, 1, 35);

SET FOREIGN_KEY_CHECKS = 1;
